export const options = [
    { value: 'No Zone', label: 'No Zone', color: '#FFFFFF' },
    { value: 'Zone 1', label: 'Zone 1', color: '#FF4242' },
    { value: 'Zone 2', label: 'Zone 2', color: '#299FFF' },
    { value: 'Zone 3', label: 'Zone 3', color: '#FFFF52' },
    { value: 'Zone 4', label: 'Zone 4', color: '#27EB33' },
    { value: 'Zone 5', label: 'Zone 5', color: '#00ffff' },
    { value: 'Zone 6', label: 'Zone 6', color: '#D742FF' },
    { value: 'Zone 7', label: 'Zone 7', color: '#FF9329' },
    { value: 'Zone 8', label: 'Zone 8', color: '#ED2397' },
    { value: 'Zone 9', label: 'Zone 9', color: '#30E5BE' },
    { value: 'Zone 10', label: 'Zone 10', color: '#BFF748' },
    { value: 'Zone 11', label: 'Zone 11', color: '#FFA77B' },
    { value: 'Zone 12', label: 'Zone 12', color: '#817BFF' },
    { value: 'Zone 13', label: 'Zone 13', color: '#FF7BAD' },
    { value: 'Zone 14', label: 'Zone 14', color: '#6BC2FF' },
    { value: 'Zone 15', label: 'Zone 15', color: '#D732FF' },
    { value: 'Zone 16', label: 'Zone 16', color: '#3F9229' },
    { value: 'Zone 17', label: 'Zone 17', color: '#EC2897' },
    { value: 'Zone 18', label: 'Zone 18', color: '#32EFBE' },
    { value: 'Zone 19', label: 'Zone 19', color: '#CFF148' },
    { value: 'Zone 20', label: 'Zone 20', color: '#FFA27B' },
    { value: 'Zone 21', label: 'Zone 21', color: '#8FCBFF' },
    { value: 'Zone 22', label: 'Zone 22', color: '#FCFBAD' },
    { value: 'Zone 23', label: 'Zone 23', color: '#6BCDEF' },
    { value: 'Zone 24', label: 'Zone 24', color: '#6BC23C' },
    { value: 'Zone 25', label: 'Zone 25', color: '#6FF2FF' },
];

export const autoRepairData = [
  { title: '2" Mill & Overlay', repairType: 'Capital', color: '#FF4242' },
  { title: '4" Asphalt Remove & Replace', repairType: 'Capital', color: '#27EB33' },
  { title: '5" Asphalt Remove & Replace', repairType: 'Capital', color: '#ED2397' },
  { title: '6" Asphalt Remove & Replace', repairType: 'Capital', color: '#299FFF' },
  { title: '8" Concrete Remove & Replace', repairType: 'Capital', color: '#00ffff' },
  { title: '8" Dolly Pad', repairType: 'Capital', color: '#00ffff' },
  { title: 'Seal Coat', repairType: 'Maintenance', color: '#D742FF' },
  { title: 'Asphalt Crack Seal', repairType: 'Maintenance', color: '#FFFF52' },
  { title: 'Concrete Crack Seal', repairType: 'Maintenance', color: '#00ffff' },
  { title: 'Restripe Affected Areas', repairType: 'Maintenance', color: '#ffffff' },
  { title: '8 x 8 Concrete Collar', repairType: 'Capital', color: '#FF9329' },
  { title: 'Concrete Joint Seal', repairType: 'Maintenance', color: '#00ffff' },
];
