export const FETCH_SITE_MAP_DATA = 'FETCH_SITE_MAP_DATA';
export const FETCH_SITE_MAP_DATA_SUCCESSFULLY = 'FETCH_SITE_MAP_DATA_SUCCESSFULLY';
export const FETCH_SITE_MAP_DATA_FAIL = 'FETCH_SITE_DETAIL_FAIL';

export const SUBMIT_SITE_MAP_DATA = 'SUBMIT_SITE_MAP_DATA';
export const SUBMIT_SITE_MAP_DATA_SUCCESSFULLY = 'SUBMIT_SITE_MAP_DATA_SUCCESSFULLY';
export const SUBMIT_SITE_MAP_DATA_FAIL = 'SUBMIT_SITE_MAP_DATA_FAIL';

export const FETCH_SITE_DETAIL = 'FETCH_SITE_DETAIL';
export const FETCH_SITE_DETAIL_SUCCESSFULLY = 'FETCH_SITE_DETAIL_SUCCESSFULLY';
export const FETCH_SITE_DETAIL_FAIL = 'FETCH_SITE_DETAIL_FAIL';

export const LANDSCAPING_NAME = 'LANDSCAPE';
export const HVAC_NAME = 'HVAC';
export const PAVEMENT_NAME = 'PAVEMENT';
export const ROOFING_NAME = 'ROOFING';

export const DELETE_LAYER_CONFIRMATION_MESSAGE =
  'Are you sure you want to delete this layer?';

export const MEASUREMENT_LAYER_ROOFING = 'MEASUREMENT_LAYER_ROOFING';
export const MEASUREMENT_LAYER_ROOFING_ZONE = 'MEASUREMENT_LAYER_ROOFING_ZONE';
export const MEASUREMENT_LAYER_ROOFING_REPAIR = 'MEASUREMENT_LAYER_ROOFING_REPAIR';

export const MEASUREMENT_LAYER_PAVEMENT = 'MEASUREMENT_LAYER_PAVEMENT';

export const MEASUREMENT_LAYER_LANDSCAPE = 'MEASUREMENT_LAYER_LANDSCAPE';
export const MEASUREMENT_LAYER_LANDSCAPE_ZONE = 'MEASUREMENT_LAYER_LANDSCAPE_ZONE';
export const MEASUREMENT_LAYER_LANDSCAPE_REPAIR = 'MEASUREMENT_LAYER_LANDSCAPE_REPAIR';

export const INVENTORY_ITEM_MARKER_HVAC = 'HVAC:marker';
export const INVENTORY_ITEM_POLYGON_HVAC = 'HVAC:poly';

export const INVENTORY_ITEM_MARKER_LANDSCAPE = `${LANDSCAPING_NAME}:marker`;
export const INVENTORY_ITEM_POLYGON_LANDSCAPE = `${LANDSCAPING_NAME}:poly`;

export const PCIColors = {
  Poor: '#E50200',
  Fair: '#D2BC00',
  Good: '#28BF00',
  'Not Set': '#FFFFFF',
};

export const SocketConst = {
  REQ_GET_USERS_VIEWING_MAP: 'REQ_GET_USERS_VIEWING_MAP',
  RES_GET_USERS_VIEWING_MAP: 'RES_GET_USERS_VIEWING_MAP',
  REQ_USER_STOP_VIEWING_MAP: 'REQ_USER_STOP_VIEWING_MAP',
  RES_USER_STOP_VIEWING_MAP: 'RES_USER_STOP_VIEWING_MAP',
  REQ_ALL_USERS_WORKING: 'REQ_ALL_USERS_WORKING',
  RES_ALL_USERS_WORKING: 'RES_ALL_USERS_WORKING',
  ON_GLOBAL_UPDATE: 'ON_GLOBAL_UPDATE',
  LOCALHOST: 'http://localhost:5000',
};
