export const FETCH_SITE_DETAIL = 'FETCH_SITE_DETAIL';
export const FETCH_SITE_DETAIL_SUCCESSFULLY = 'FETCH_SITE_DETAIL_SUCCESSFULLY';
export const FETCH_SITE_DETAIL_FAIL = 'FETCH_SITE_DETAIL_FAIL';

export const RESET_SHOW_MESSAGE = 'RESET_SHOW_MESSAGE';
export const CLEAR_SITE_ERROR = 'CLEAR_SITE_ERROR';
export const CHANGE_NOTE = 'CHANGE_NOTE';

export const SUBMIT_NOTE = 'SUBMIT_NOTE';
export const SUBMIT_NOTE_SUCCESSFULLY = 'SUBMIT_NOTE_SUCCESSFULLY';
export const SUBMIT_NOTE_FAIL = 'SUBMIT_NOTE_FAIL';

export const UPDATE_SITE_STATUS = 'UPDATE_SITE_STATUS';
export const UPDATE_SITE_STATUS_SUCCESSFULLY = 'UPDATE_SITE_STATUS_SUCCESSFULLY';
export const UPDATE_SITE_STATUS_FAIL = 'UPDATE_SITE_STATUS_FAIL';


export const OPEN_EDIT = 'OPEN EDIT';
export const CLOSE_EDIT = 'CLOSE EDIT';

export const EDIT_SITE_DETAIL = 'EDIT SITE DETAIL';
export const EDIT_SITE_DETAIL_SUCCESSFULLY = 'EDIT SITE DETAIL SUCCESSFULLY';
export const EDIT_SITE_DETAIL_FAIL = 'EDIT SITE DETAIL FAIL';
