version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn build
  deploy_staging:
    docker:
      - image: circleci/node:8.0.0
    working_directory: ~/repo
    steps:
      - run: npm install -g firebase-tools
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: master