export const inventoryTypeItems = [
  {
    id: 'treesId',
    name: 'Trees',
    measurement: 'Number',
    options: 'Hotspot',
    color: '#FF4242',
  },
  {
    id: 'wastewaterId',
    name: 'Wastewater Surface Area',
    measurement: 'Area',
    options: 'SF',
    color: '#299FFF',
  },
  {
    id: 'fencingId',
    name: 'Fencing',
    measurement: 'Area',
    options: 'LF',
    color: '#FFFF52',
  },
  {
    id: 'stormDrainsId',
    name: 'Storm Drains',
    measurement: 'Number',
    options: 'Hotspot',
    color: '#27EB33',
  },
  {
    id: 'flowerBedsId',
    name: 'Flower Beds',
    measurement: 'Area',
    options: 'SF',
    color: '#00ffff',
  },
  {
    id: 'detentionPondsId',
    name: 'Detention Ponds',
    measurement: 'Area',
    options: 'SF',
    color: '#D742FF',
  },
  {
    id: 'grassMowedAreaId',
    name: 'Grass Mowed Area',
    measurement: 'Area',
    options: 'SF',
    color: '#FF9329',
  },
  {
    id: 'shrubsId',
    name: 'Shrubs',
    measurement: 'Number',
    options: 'Hotspots',
    color: '#ED2397',
  },
  {
    id: 'evergreensId',
    name: 'Evergreens',
    measurement: 'Number',
    options: 'Hotspots',
    color: '#30E5BE',
  },
  {
    id: 'woodChipsId',
    name: 'Mulch, Wood Chips',
    measurement: 'Number',
    options: 'SF',
    color: '#BFF748',
  },
  {
    id: 'stoneId',
    name: 'Mulch, Stone',
    measurement: 'Number',
    options: 'SF',
    color: '#FFA77B',
  },
  {
    id: 'ripRapId',
    name: 'Rip Rap',
    measurement: 'Number',
    options: 'SF',
    color: '#817BFF',
  },
  {
    id: 'cobbleStonePaversId',
    name: 'Cobblestone Pavers',
    measurement: 'Number',
    options: 'SF',
    color: '#FF7BAD',
  },
  {
    id: 'irrigationId',
    name: 'Irrigation',
    measurement: 'Number',
    options: 'Hotspot',
    color: '#6BC2FF',
  },
];

